### ISSUE TITLE
bug: typing an amount greater than balance still shows "seems OK"

### ISSUE THREAD

**Issue by ShieldCoin** [ShieldCoin/WebWallet#4]

**Comment by Xolrium** [comment]
<div class="input-field col s10">
              <input id="sendamount" type="number" name="sendamount" required="" class="validate" min="1" step="0.5">
              <label for="sendamount" data-error="Please fill in a valid value" data-success="Seems OK">Amount</label>
            </div>

Not sure if this might be helpful, but I don't see a "max" variable that'll make sure the user can't exceed his balance.

**Comment by ShieldCoin** [comment]
Yeah, I'll need to change the max depending on the balance with Javascript

**Comment by ShieldCoin** [comment]
Will be fixed in the coming commit
